### ISSUE TITLE
Install not working

### ISSUE THREAD

**Issue by mherschl** [YichaoOU/easy_prime#4]
I have tried running `conda create -n pegDesign -c cheng_lab easy_prime` on both mac and linux, and on both machines, it is failing to solve the environment, saying that it's found conflicts, but not listing any packages. Any idea what might be causing this?
![image](https://user-images.githubusercontent.com/70413153/145937729-22c47a2d-055e-41a9-b9ed-6d75b6260b9f.png)

**Comment by YichaoOU** [comment]
Hello,

Can you show the `conda info`?

Try if these things help:

```
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
conda config --set channel_priority flexible
conda create -n genome_editing -c cheng_lab easy_prime
```

Best,
Yichao

**Comment by mherschl** [comment]
Thank you, adding those channels worked for the installation, but when running the test, I am getting another error: `AttributeError: 'XGBModel' object has no attribute 'enable_categorical'`
![image](https://user-images.githubusercontent.com/70413153/145943822-5b1d2ca3-f49d-4dc6-b690-9876ba3018e1.png)

**Comment by YichaoOU** [comment]
Can you try `pip install xgboost==1.4.0`?

**Comment by mherschl** [comment]
> Can you try `pip install xgboost==1.4.0`?

This fixed the error, and everything seems to be running smoothly. Thank you for the quick solutions!
